### ISSUE TITLE
Improve button design

### ISSUE THREAD

**Issue by itshypon** [akshat-jn-crypto/Wordle-clone#14]
I would like to improve button design which will look more better and fits the website theme. Thanks!

**Comment by akshat-jn-crypto** [comment]
Cool go ahead.

**Comment by akshat-jn-crypto** [comment]
Attach Screenshot of the changes in the pull request.

**Comment by itshypon** [comment]
Kindly change label to hacktoberfest or hacktoberfest-accepted
